'use strict';
Object.defineProperty(exports, '__esModule', { value: true });
var index_1 = require('../index');
// const boxSchema = schema<Box<any>>();
// console.log(JSON.stringify(boxSchema, null, 2));
// console.log('-'.repeat(80));
// const bigboxSchema = schema<BigBox<any>>();
// console.log(JSON.stringify(bigboxSchema, null, 2));
// console.log('-'.repeat(80));
var userSchema = index_1.schema();
// console.log(JSON.stringify(userSchema, null, 2));
// console.log('-'.repeat(80));
