'use strict';
Object.defineProperty(exports, '__esModule', { value: true });
var index_1 = require('../index');
var boxSchema = index_1.schema();
console.log(JSON.stringify(boxSchema, null, 2));
console.log('-'.repeat(80));
var markerSchema = index_1.schema();
console.log(JSON.stringify(markerSchema, null, 2));
console.log('-'.repeat(80));
var userSchema = index_1.schema();
console.log(JSON.stringify(userSchema, null, 2));
console.log('-'.repeat(80));
var specialSchema = index_1.schema();
console.log(JSON.stringify(specialSchema, null, 2));
console.log('-'.repeat(80));
var withTypeLiteralSchema = index_1.schema();
console.log(JSON.stringify(withTypeLiteralSchema, null, 2));
console.log('-'.repeat(80));
